### ISSUE TITLE
User Can Add Lab with Invalid Descriptor in Lab Deployment

### ISSUE THREAD

**Issue by ravikiran2020** [virtual-labs/app-lab-deployment-web#3]
User Can Add Lab with Invalid Descriptor in Lab Deployment

Steps to Reproduce:

1. Log in to the lab deployment system.
2. Navigate to the lab deployment page.
3. Click on the option to add a new lab for deployment.
4. Enter an invalid descriptor for the lab.
5. Proceed with the lab deployment process.
6. Observe that the system allows the user to proceed with deployment despite the invalid descriptor.

Expected Behavior:

The system should not allow the user to proceed with lab deployment if the descriptor provided is invalid. It should prompt the user to correct the descriptor before proceeding further and only allow if the descriptor is fixed. 

Actual Behavior:
The system allows the user to add the lab for deployment with an invalid descriptor. The failure occurs only when the deployment is processed, which is too late.

**Comment by chir263** [comment]
Resolved this bug. Please review it.

**Comment by ravikiran2020** [comment]
Tested and working as expected.
